[project]
name = "anxiety"
version = "0.1.2"
description = "Personal project to keep my fucking download folder organized for once."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer>=0.21.1",
    "watchdog>=6.0.0",
]


[project.scripts]
anxiety = "anxiety.main:app"
