[project]
name = "anxiety"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "typer>=0.21.1",
    "watchdog>=6.0.0",
]


[project.scripts]
anxiety = "anxiety.main:app"
